pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn -f java-tomcat/pom.xml clean package'
            }
            post{
                success{
                    archiveArtifacts artifacts: '**/*.war', followSymlinks: false
                }
            }
        }
        stage('staging'){
            steps{
                deploy adapters: [tomcat8(credentialsId: '4b9202af-f3fc-449f-ab1d-563552e1c285', path: '', url: '')], contextPath: null, war: '**/*.war'
            }
        }
    }
}
